#################################################
## Mongo Express Helm task settings
#################################################

#####################
## Mongo Express settings
#####################

mongoExpress:
  image:
    repository: mongo-express
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  containerPort: 8081
  autoscaling:
    enabled: false
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
  service:
    enabled: true
    type: NodePort
    port: 8081
    nodePort: 30000
    annotations: {}


#####################
## Ingress settings
#####################

ingress:
  enabled: false
  className: nginx