apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  type: {{ .Values.mongoExpress.service.type }}
  ports:
    - port: {{ .Values.mongoExpress.service.port }}
      targetPort: {{ .Values.mongoExpress.containerPort }}
      nodePort: {{ .Values.mongoExpress.service.nodePort }}
  selector:
    app: mongo-express
