#################################################
## Feathers Quasar Boilerplate Helm task settings
#################################################

#####################
## Global settings
#####################

repository:
  url: codask/feathers-quasar-boilerplate

namespace: dev

serviceAccount:
  create: false

#####################
## Databases settings
#####################

mongodb:
  enabled: true
  useStatefulSet: true
  auth: 
    enabled: false
  fullnameOverride: mongodb
  service:
    port: 27017

#####################
## App settings
#####################

feathersQuasarBoilerplate:
  image:
    repository: codask/feathers-quasar-boilerplate
    tag: dev
    pullPolicy: Always
  replicaCount: 1
  autoscaling:
    enabled: false
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
  service:
    enabled: true
    type: NodePort
    port: 8081
    nodePort: 30001                                                       
    annotations: {}