version: '3.3'

services:
  feathers-quasar-boilerplate:
    image: codask/feathers-quasar-boilerplate:dev
    environment:
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASWORD=${GMAIL_PASWORD}
    ports:
      - "8081:8081"
    networks:
      - feathers-quasar-boilerplate
  mongodb:
    image: mongo:4.2
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - feathers-quasar-boilerplate

volumes:
  mongodb:

networks:
  feathers-quasar-boilerplate: