name: Build & Deploy
on: [push]

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, '[skip test]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses:  actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Run tests
        run: |
          cd api
          yarn
          yarn test:server
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASWORD: ${{ secrets.GMAIL_PASWORD }}
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ce7b70a1429216c395464c7031e47ed2a99b93ca17b8f08ba1396eb670fbc5a9