name: Build & Deploy
on: [push]

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, '[skip test]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses:  actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '4.2'
      - name: Run tests
        run: |
          cd api
          yarn
          yarn test
